version: '3.8'
services:
  app:
    container_name: shopping-cart-app
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: shopping-cart-db
    image: mysql
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    container_name: shopping-cart-phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db_data:
