version: '3.8'
services:
  php-apache-2:
    container_name: php-apache-two
    build:
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    links:
      - db
  db:
    image: mysql
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "react_insta_db_data:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - db
    environment:
      PMA_HOST: db2
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
    react_insta_db_data:
